"""
Background Worker

Consumes tasks_queue.

Current implementation:
    generate_pdf

Worker generates PDF and uploads it to Django.
"""

import asyncio
import json
import os
import time

import httpx
import redis.asyncio as redis

from redis.exceptions import TimeoutError as RedisTimeoutError
from dotenv import load_dotenv

from reportlab.pdfgen import canvas

load_dotenv()


REDIS_URL = os.environ.get(
    "REDIS_URL",
    "redis://localhost:6379/0"
)

MAIN_SERVICE_URL = os.environ.get(
    "MAIN_SERVICE_URL",
    "http://main-service:8000"
)

QUEUE_NAME = "tasks_queue"

RESULT_TTL_SECONDS = 3600

HEARTBEAT_KEY = (
    f"heartbeat:background-worker:"
    f"{os.environ.get('HOSTNAME', 'unknown')}"
)


# ============================================================
# PDF GENERATION
# ============================================================

def generate_pdf(
    job_id: str,
    name: str,
    message: str,
) -> str:

    output_dir = "/tmp/generated_pdfs"

    os.makedirs(
        output_dir,
        exist_ok=True,
    )

    file_path = os.path.join(
        output_dir,
        f"{job_id}.pdf",
    )

    pdf = canvas.Canvas(
        file_path
    )

    pdf.setTitle(
        f"Job {job_id}"
    )

    pdf.setFont(
        "Helvetica-Bold",
        20,
    )

    pdf.drawString(
        100,
        750,
        "CWA Ship Karachi 2026",
    )

    pdf.setFont(
        "Helvetica",
        14,
    )

    pdf.drawString(
        100,
        700,
        f"Name: {name}",
    )

    pdf.drawString(
        100,
        670,
        f"Message: {message}",
    )

    pdf.drawString(
        100,
        620,
        f"Job ID: {job_id}",
    )

    pdf.drawString(
        100,
        570,
        "Generated by Background Worker",
    )

    pdf.save()

    return file_path


# ============================================================
# PROCESS JOB
# ============================================================

async def process_job(
    r: redis.Redis,
    job: dict,
):

    job_id = job["job_id"]

    task_type = job.get(
        "type"
    )

    try:

        print(
            f"[BACKGROUND WORKER] "
            f"Processing job: {job_id}"
        )

        # ====================================================
        # GENERATE PDF
        # ====================================================

        if task_type == "generate_pdf":

            input_data = job.get(
                "input",
                {}
            )

            name = input_data.get(
                "name",
                "Unknown"
            )

            message = input_data.get(
                "message",
                "Hello"
            )

            file_path = generate_pdf(
                job_id=job_id,
                name=name,
                message=message,
            )

            print(
                f"[PDF] Generated: {file_path}"
            )

            # =================================================
            # SEND PDF TO DJANGO
            # =================================================

            callback_url = (
                f"{MAIN_SERVICE_URL}"
                f"/api/internal/"
                f"worker-pdf-result/"
                f"{job_id}"
            )

            async with httpx.AsyncClient(
                timeout=30
            ) as client:

                with open(
                    file_path,
                    "rb"
                ) as pdf_file:

                    response = await client.post(
                        callback_url,

                        files={
                            "file": (
                                f"{job_id}.pdf",
                                pdf_file,
                                "application/pdf",
                            )
                        },
                    )

                response.raise_for_status()

            print(
                f"[PDF] Uploaded to Django: "
                f"{job_id}"
            )

            # =================================================
            # DON'T STORE THE WORKER PATH
            # =================================================
            #
            # Django now owns the PDF.
            #
            # We only store metadata in Redis.


            print(
                f"[BACKGROUND WORKER] "
                f"Completed: {job_id}"
            )

            return

        # ====================================================
        # UNKNOWN JOB
        # ====================================================

        raise ValueError(
            f"Unknown task type: {task_type}"
        )

    except Exception as exc:

        print(
            f"[BACKGROUND WORKER] "
            f"Job failed: {job_id}: {exc}"
        )

        await r.set(
            f"result:{job_id}",

            json.dumps(
                {
                    "status": "error",
                    "error": str(exc),
                }
            ),

            ex=RESULT_TTL_SECONDS,
        )


# ============================================================
# HEARTBEAT
# ============================================================

async def heartbeat_loop(
    r: redis.Redis
):

    while True:

        await r.set(
            HEARTBEAT_KEY,
            str(time.time()),
            ex=15,
        )

        await asyncio.sleep(5)


# ============================================================
# MAIN LOOP
# ============================================================

async def main():

    r = redis.from_url(
        REDIS_URL
    )

    asyncio.create_task(
        heartbeat_loop(r)
    )

    print(
        f"Background worker started, "
        f"listening on '{QUEUE_NAME}'"
    )

    while True:

        try:

            job_data = await r.blpop(
                QUEUE_NAME,
                timeout=5,
            )

            if not job_data:
                continue

            _, raw_job = job_data

            job = json.loads(
                raw_job
            )

            asyncio.create_task(
                process_job(
                    r,
                    job,
                )
            )

        except (
            RedisTimeoutError,
            TimeoutError,
        ):

            continue

        except Exception as exc:

            print(
                f"Worker polling error: {exc}"
            )

            await asyncio.sleep(1)


if __name__ == "__main__":

    asyncio.run(
        main()
    )
